export const transforms = [
    ([x, y, z]) => [x, y, z],
    ([x, y, z]) => [x, y, -z],
    ([x, y, z]) => [x, -y, z],
    ([x, y, z]) => [x, -y, -z],
    ([x, y, z]) => [-x, y, z],
    ([x, y, z]) => [-x, y, -z],
    ([x, y, z]) => [-x, -y, z],
    ([x, y, z]) => [-x, -y, -z],
    ([x, y, z]) => [z, x, y],
    ([x, y, z]) => [z, x, -y],
    ([x, y, z]) => [z, -x, y],
    ([x, y, z]) => [z, -x, -y],
    ([x, y, z]) => [-z, x, y],
    ([x, y, z]) => [-z, x, -y],
    ([x, y, z]) => [-z, -x, y],
    ([x, y, z]) => [-z, -x, -y],
    ([x, y, z]) => [y, z, x],
    ([x, y, z]) => [y, z, -x],
    ([x, y, z]) => [y, -z, x],
    ([x, y, z]) => [y, -z, -x],
    ([x, y, z]) => [-y, z, x],
    ([x, y, z]) => [-y, z, -x],
    ([x, y, z]) => [-y, -z, x],
    ([x, y, z]) => [-y, -z, -x],
    ([x, y, z]) => [x, z, y],
    ([x, y, z]) => [x, z, -y],
    ([x, y, z]) => [x, -z, y],
    ([x, y, z]) => [x, -z, -y],
    ([x, y, z]) => [-x, z, y],
    ([x, y, z]) => [-x, z, -y],
    ([x, y, z]) => [-x, -z, y],
    ([x, y, z]) => [-x, -z, -y],
    ([x, y, z]) => [y, x, z],
    ([x, y, z]) => [y, x, -z],
    ([x, y, z]) => [y, -x, z],
    ([x, y, z]) => [y, -x, -z],
    ([x, y, z]) => [-y, x, z],
    ([x, y, z]) => [-y, x, -z],
    ([x, y, z]) => [-y, -x, z],
    ([x, y, z]) => [-y, -x, -z],
    ([x, y, z]) => [z, y, x],
    ([x, y, z]) => [z, y, -x],
    ([x, y, z]) => [z, -y, x],
    ([x, y, z]) => [z, -y, -x],
    ([x, y, z]) => [-z, y, x],
    ([x, y, z]) => [-z, y, -x],
    ([x, y, z]) => [-z, -y, x],
    ([x, y, z]) => [-z, -y, -x],
];

export function addPositions(known, possible) {
    return [known[0] + possible[0], known[1] + possible[1], known[2] + possible[2]];
}
export function subtractPositions(known, possible) {
    return [known[0] - possible[0], known[1] - possible[1], known[2] - possible[2]];
}
